name: stock_rebalence
description: "stock"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^29.2.7 # 차트 패키지
  cupertino_icons: ^1.0.8
  http: ^1.2.1 # HTTP 통신을 위한 패키지
  shared_preferences: ^2.2.3 # 로컬 저장을 위한 패키지
  alpha_vantage_api: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true




